export const BASE_URL_UA = 'https://romsat.ua';
// export const BASE_URL_RU = 'https://turboam.com.ua/ru';
// export const API_URL='api_live_search';
// export const CATALOG_URL='katalog'

export const CATEGORIES_URL = [
  'posud',
  'nastinniy-dekor',
  'zapisni-knizhki',
  'rizne',
  'golovni-ubori',
  'tolstovki',
  'futbolki',
  'shkarpetki',
  'gamantsi',
  'breloki',
  'znachki',
  'medalyoni',
  'nashivki',
  'ryukzaki',
  'figurki-ta-statuetki',
  'igrovi-manipulyatori',
  'aksesuari-do-konsoley',
  'navushniki',
  'kompyuterni-mishi',
  'igrovi-poverkhni',
];

export const ITEM_COMMON = {
  Артикул: null,
  'Родительский артикул': null,
  'Артикул модели': null,
  'Название модификации (UA)': null,
  'Название модификации (RU)': null,
  'Название (UA)': null,
  'Название (RU)': null,
  Бренд: null,
  Раздел: null,
  Цена: null,
  'Старая цена': null,
  Валюта: 'UAH',
  Отображать: 'Да',
  Наличие: 'В наявності',
  'Дополнительные разделы': null,
  Фото: null,
  Галерея: null,
  'Обзор 360': null,
  Алиас: null,
  Ссылка: null,
  'Дата добавления': null,
  'HTML title (UA)': null,
  'HTML title (RU)': null,
  'META keywords (UA)': null,
  'META keywords (RU)': null,
  'META description (UA)': null,
  'META description (RU)': null,
  'h1 заголовок (UA)': null,
  'h1 заголовок (RU)': null,
  Поставщик: null,
  Иконки: null,
  'Скидка %': 0,
  Популярность: 0,
  Количество: 0,
  'Описание товара (UA)': null,
  'Описание товара (RU)': null,
  'Короткое описание (UA)': null,
  'Короткое описание (RU)': null,
  Цвет: null,
  'Тип гарантии': null,
  'Гарантийный срок, мес.': null,
  'Дата и время окончания акции': null,
  'Текст акции (UA)': null,
  'Текст акции (RU)': null,
  'Описание для маркетплейсов (UA)': null,
  'Описание для маркетплейсов (RU)': null,
  'Выгружать на маркетплейсы': null,
  'Состояние товара': null,
  'Только для взрослых': 'Нет',
  'Код УКТ ВЭД': null,
  'Уникальный код налога': null,
  Штрихкод: null,
  'Код производителя товара (MPN)': null,
  'На складе для Prom': null,
  'Электронный товар': null,
  "Об'єм пам'яті": null,
  'Аксессуары(разделы)': null,
};

export const ITEM_SPEC = {
  Артикул: null,
  'Название(UA)': null,
  'Название(RU)': null,
  'Тип(UA)': null,
  'Тип(RU)': null,
  'Напрямок(UA)': null,
  'Напрямок(RU)': null,
  'Тематика(UA)': null,
  'Тематика(RU)': null,
  'Призначення(UA)': null,
  'Призначення(RU)': null,
  'Матеріал(UA)': null,
  'Матеріал(RU)': null,
  "Об'єм(UA)": null,
  "Об'єм(RU)": null,
  'Особливості(UA)': null,
  'Особливості(RU)': null,
  'Комплектація(UA)': null,
  'Комплектація(RU)': null,
  'Бренд(UA)': null,
  'Бренд(RU)': null,
  'Країна реєстрації бренду(UA)': null,
  'Країна реєстрації бренду(RU)': null,
  'Колір(UA)': null,
  'Колір(RU)': null,
};
